# Concouse CI Pipeline definition for Spring Boot

resources:
  - name: project-app
    type: git
    source:
      uri: ((repository-url))
      branch: ((branch))
      email: ((git-email)) 
      username: ((git-username))
      password: ((git-password))
  - name: app-image
    type: docker-image
    icon: docker
    source:
      email: ((docker-email))
      username: ((docker-username))
      password: ((docker-password))
      repository: ((docker-repo))

jobs:
- name: tests
  plan:
  - get: project-app
    trigger: true

  - task: test
    config:
      inputs:
        - name: project-app
      outputs:
        - name: project-app
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: maven
          tag: 3-jdk-8
      run:
        path: mvn
        args: [test]
        dir: project-app

  - task: debug-test
    config:
      platform: linux
      inputs:
        - name: project-app
      image_resource:
        type: registry-image
        source:
          repository: alpine
      run:
        path: ls
        dir: project-app

- name: build-app
  plan:
  - get: project-app
    trigger: true
    passed: [tests]

    #- task: build
    #- config:
    #-   inputs:
    #-     - name: project-app
    #-   outputs:
    #-     - name: project-app
    #-   platform: linux     
    #-   image_resource:
    #-     type: registry-image
    #-     source:
    #-       repository: maven
    #-       tag: 3-jdk-8
    #-   run:      
    #-     path: mvn
    #-     args: [clean, install]
    #-     dir: project-app

    #- task: debug-build
    #- config:
    #-   platform: linux
    #-   inputs:
    #-     - name: project-app
    #-   image_resource:
    #-     type: registry-image
    #-     source:
    #-       repository: alpine
    #-   run:
    #-     path: ls
    #-     dir: project-app

  - put: app-image
    params:
      build: project-app
