# Concouse CI Pipeline definition for Spring Boot

resources:
  - name: project-app
    type: git
    source:
      uri: (( repository-url ))
      branch: (( branch ))
      email: (( git-email )) 
      username: (( git-username ))
      password: (( git-password ))



  - name: project-ci
    type: git
    source:
      uri: (( repository-url ))
      branch: (( branch ))
      email: (( git-email ))
      username: (( git-username ))
      password: (( git-password ))
      paths:
        - pipelines

  - name: openjdk
    type: registry-image
    icon: docker
    source:
      repository: openjdk
      tag: "8-jdk-alpine"     
    
jobs:
- name: build
  plan:
  - get: project-app
    trigger: true
  - get: project-ci
    trigger: true
  - get: openjdk
    trigger : true   
  - task: build
    file: project-ci/tasks/build-main.yml

