# Concouse CI Pipeline definition for Spring Boot

resources:
  - name: project-app
    type: git
    source:
      uri: ((repository-url))
      branch: ((branch))
      email: ((git-email)) 
      username: ((git-username))
      password: ((git-password))
  - name: app-image
    type: docker-image
    icon: docker
    source:
      email: ((docker-email))
      username: ((docker-username))
      password: ((docker-password))
      repository: carfaoui/spring-app

jobs:
- name: build
  plan:
  - get: project-app
    trigger: true

  - task: mvn install
    config:
      platform: linux
      inputs:
        - name: project-app
      outputs:
        - name: project-app
      image_resource:
        type: registry-image
        source:
          repository: maven
          tag: 3-jdk-8
      run:
        path: mvn
        args: [clean, install]
        dir: project-app

  - task: debug
    config:
      platform: linux
      inputs:
        - name: project-app
      image_resource:
        type: registry-image
        source:
          repository: alpine
      run:
        path: ls
        dir: project-app

  - put: app-image
    params:
      build: project-app
